"""Regression checks for structured blueprint safety gates."""
import zipfile
from pathlib import Path

import pytest
from docx import Document

pytestmark = pytest.mark.unit


def test_quality_gate_blocks_raw_markdown_and_prohibited_defaults(sample_params_depository):
    from src.structured_blueprint import normalise_structured_result, run_quality_gate

    raw = {
        "summary": "## Summary\n\nUse default value 'Unknown' for mandatory account holder name.",
        "architecture": "### Architecture\n\nUS place of birth should not be in CRS logic.",
        "field_catalog": "| Field | Rule |\n|---|---|\n| Name | Use default values |",
        "downstream": "Portal details are [INFERRED].",
        "risk_flags": "1. Missing self-certification.",
        "classification": "Renew every 3 years.",
        "governance": "Use last known values.",
        "testing": "No TIN scenario.",
    }
    structured = normalise_structured_result(raw, sample_params_depository, {})
    quality = run_quality_gate(structured)
    all_text = str(structured).lower()

    assert quality["passed"]
    assert "use default value 'unknown'" not in all_text
    assert "use default values" not in all_text
    assert "use last known values" not in all_text
    assert "renew every 3 years" not in all_text
    assert "local confirmation required" in all_text


def test_generate_fsd_adds_structured_blueprint_and_quality_gate(mock_fsd_response, sample_params_depository, tmp_cache_dir):
    from unittest.mock import patch
    from src.fsd_generator import generate_fsd

    with patch("src.fsd_generator.call_llm", return_value=(mock_fsd_response, "Groq", "Blueprint generated.")):
        result = generate_fsd(sample_params_depository, None)

    assert "_structured_blueprint" in result
    assert "_quality_gate" in result
    assert result["_quality_gate"]["passed"]
    assert "Evidence status" in result["summary"]
    assert "Needs verification" in result["evidence"]


def test_docx_builder_does_not_emit_raw_markdown_or_outdated_branding(mock_fsd_response, sample_params_depository, tmp_path, monkeypatch):
    from unittest.mock import patch
    from src.fsd_generator import generate_fsd
    from src.docx_builder import build_docx

    monkeypatch.chdir(tmp_path)
    with patch("src.fsd_generator.call_llm", return_value=(mock_fsd_response, "Generated by Groq llama-3.3-70b-versatile", "Blueprint generated.")):
        result = generate_fsd(sample_params_depository, None)
    path = build_docx(result, sample_params_depository)
    doc = Document(path)
    text = "\n".join(p.text for p in doc.paragraphs)
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                text += "\n" + cell.text

    assert "###" not in text
    assert "|---" not in text
    assert "free tool" not in text.lower()
    assert "llama" not in text.lower()
    assert "Generated by Groq" not in text
    assert "Use default value" not in text
    assert "Implementation draft" in text
    assert "Draft for professional review" not in text
    assert "Pre-download Quality Gate" not in text


def test_docx_contains_governance_tables_as_separate_tables(mock_fsd_response, sample_params_investment, tmp_path, monkeypatch):
    from src.docx_builder import build_docx
    from src.structured_blueprint import normalise_structured_result

    monkeypatch.chdir(tmp_path)
    raw = dict(mock_fsd_response)
    raw["governance"] = (
        "## Governance\n\n"
        "### Stakeholder RACI Map\n"
        "| Function | R | A | C | I |\n|---|---|---|---|---|\n| Data extraction | Data Team | Compliance | IT | Ops |\n\n"
        "### Data Retention Requirements\n"
        "| Record | Period | Owner |\n|---|---|---|\n| CRS report | Local confirmation required | Compliance |\n\n"
        "### Implementation Timeline\n"
        "| Target Date | Milestone | Owner | Dependencies |\n|---|---|---|---|\n| Local confirmation required | Submit report | Compliance | Validation complete |"
    )
    structured = normalise_structured_result(raw, sample_params_investment, {})
    result = {"_structured_blueprint": structured, "_quality_gate": {"passed": True, "checks": []}}
    path = build_docx(result, sample_params_investment)
    doc = Document(path)

    table_headers = []
    for table in doc.tables:
        if table.rows:
            table_headers.append(tuple(cell.text for cell in table.rows[0].cells))

    assert ("Function", "R", "A", "C", "I", "Evidence Status") in table_headers
    assert ("Record", "Period", "Owner", "Evidence Status") in table_headers
    assert ("Target Date", "Milestone", "Owner", "Dependencies", "Evidence Status") in table_headers
