"""Multi-LLM routing: weighted random (60% Groq 70b / 40% Gemini Flash) -> Groq 8b fallback."""
import os
import json
import time
import random

GROQ_KEY = os.environ.get("GROQ_API_KEY", "")
GEMINI_KEY = os.environ.get("GEMINI_API_KEY", "")

STATUS_MESSAGES = {
    "groq_rate_limited": "Groq is at capacity — switching to Gemini Flash.",
    "gemini_active": "High traffic — switching to a faster model.",
    "groq_8b_active": "Retrying with lightweight model.",
    "all_failed": "All inference engines are currently unavailable. Please try again in a few minutes.",
}

SYSTEM_PROMPT = (
    "You are a senior CRS (Common Reporting Standard) compliance consultant with 15 years of experience "
    "at major financial institutions. You produce implementation blueprints for compliance, engineering and "
    "operations teams. Always output valid JSON only, following the user-provided schema exactly. "
    "Do not use markdown, pipe tables, code fences or prose outside JSON. Mark every material rule with one "
    "of these evidence statuses: Verified, User input, Inferred, Needs verification. Never fabricate "
    "local filing deadlines, portal details, error codes, penalties, or default values for mandatory data. "
    "Write in clear professional English. Do not use em dashes. Use standard hyphens or rewrite sentences instead."
)


def _call_groq(prompt: str, model: str) -> dict | None:
    if not GROQ_KEY:
        return None
    try:
        from groq import Groq
        client = Groq(api_key=GROQ_KEY)
        resp = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            response_format={"type": "json_object"},
            temperature=0.3,
            max_tokens=8192,
        )
        text = resp.choices[0].message.content
        return json.loads(text)
    except Exception as e:
        if "rate" in str(e).lower() or "429" in str(e):
            raise Exception("rate limited") from e
        return None


def _call_gemini(prompt: str) -> dict | None:
    if not GEMINI_KEY:
        return None
    try:
        from google import genai
        from google.genai import types
        client = genai.Client(api_key=GEMINI_KEY)
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_PROMPT,
                response_mime_type="application/json",
                temperature=0.3,
                max_output_tokens=8192,
            ),
        )
        return json.loads(response.text)
    except Exception:
        return None


def call_llm(prompt: str, status_callback=None) -> tuple[dict | None, str, str]:
    """
    Returns (result_dict, model_attribution, status_message).
    Weighted random primary: 60% Groq llama-3.3-70b, 40% Gemini Flash.
    Falls back to the other primary on failure, then Groq 8b as last resort.
    """
    def _update(msg):
        if status_callback:
            status_callback(msg)

    use_groq_first = random.random() < 0.6

    if use_groq_first:
        try:
            result = _call_groq(prompt, "llama-3.3-70b-versatile")
            if result:
                return result, "Generated by Groq llama-3.3-70b-versatile", "Blueprint generated."
        except Exception as e:
            if "rate" in str(e).lower():
                _update(STATUS_MESSAGES["groq_rate_limited"])
            time.sleep(1)

        result = _call_gemini(prompt)
        if result:
            return result, "Generated by Gemini 2.0 Flash", "Blueprint generated."
    else:
        result = _call_gemini(prompt)
        if result:
            return result, "Generated by Gemini 2.0 Flash", "Blueprint generated."

        _update(STATUS_MESSAGES["gemini_active"])
        try:
            result = _call_groq(prompt, "llama-3.3-70b-versatile")
            if result:
                return result, "Generated by Groq llama-3.3-70b-versatile", "Blueprint generated."
        except Exception as e:
            if "rate" in str(e).lower():
                _update(STATUS_MESSAGES["groq_rate_limited"])
            time.sleep(1)

    # Last resort: Groq 8b
    _update(STATUS_MESSAGES["groq_8b_active"])
    try:
        result = _call_groq(prompt, "llama-3.1-8b-instant")
        if result:
            return result, "Generated by Groq llama-3.1-8b-instant", "Blueprint generated."
    except Exception:
        pass

    return None, "", STATUS_MESSAGES["all_failed"]
