name: Sync to HuggingFace Spaces

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HuggingFace Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "amegoalter@gmail.com"
          git config --global user.name "Abhinit Sen"
          git remote add hf https://sataDientist:${HF_TOKEN}@huggingface.co/spaces/sataDientist/crs-fsd-generator
          git push hf main --force
